name: operator-agent
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: dexters-lab-ai/Nexus
  dockerfile_path: Dockerfile
  http_port: 3420
  instance_size_slug: professional-xs
  instance_count: 2
  run_command: node --max-old-space-size=4096 server.js
  
  # Environment variables
  envs:
    # Server Configuration
    - key: NODE_ENV
      value: production
    - key: PORT
      value: '3420'
    - key: NODE_OPTIONS
      value: --max-old-space-size=4096
    
    # API Configuration
    - key: VITE_API_URL
      value: https://operator-344ej.ondigitalocean.app
    - key: VITE_WS_URL
      value: wss://operator-344ej.ondigitalocean.app
    - key: VITE_FRONTEND_URL
      value: https://operator-344ej.ondigitalocean.app
    - key: API_URL
      value: https://operator-344ej.ondigitalocean.app
    - key: FRONTEND_URL
      value: https://operator-344ej.ondigitalocean.app
    - key: WS_URL
      value: wss://operator-344ej.ondigitalocean.app
    
    # Database
    - key: MONGO_URI
      value: ${MONGO_URI}
      scope: RUN_AND_BUILD_TIME
    
    # Session & Security
    - key: SESSION_SECRET
      value: ${SESSION_SECRET}
      scope: RUN_AND_BUILD_TIME
    - key: COOKIE_DOMAIN
      value: operator-344ej.ondigitalocean.app
    - key: SECURE_COOKIES
      value: 'true'
    - key: SAME_SITE_COOKIE
      value: 'none'  # Required for cross-site cookies
    
    # API Keys
    - key: OPENAI_API_KEY
      value: ${OPENAI_API_KEY}
      scope: RUN_AND_BUILD_TIME
    - key: HF_API_KEY
      value: ${HF_API_KEY}
      scope: RUN_AND_BUILD_TIME
    - key: GOOGLE_API_KEY_FILE
      value: config/google-key.json
    
    # Webhook & WebSocket
    - key: WEBHOOK_URL
      value: https://operator-344ej.ondigitalocean.app/api/webhook
    - key: WEBHOOK_SECRET
      value: ${WEBHOOK_SECRET}
      scope: RUN_AND_BUILD_TIME
    - key: OPERATOR_APP_WS_URL
      value: wss://operator-344ej.ondigitalocean.app/ws
    - key: WS_SECRET
      value: ${WS_SECRET}
      scope: RUN_AND_BUILD_TIME
    
    # Midscene Configuration
    - key: MIDSCENE_MODEL_NAME
      value: gpt-4o-mini
    - key: MIDSCENE_RUN_DIR
      value: /app/nexus_run
    
    # Additional required environment variables
    - key: JWT_SECRET
      value: ${JWT_SECRET}
      scope: RUN_AND_BUILD_TIME
    - key: COOKIE_DOMAIN
      value: operator-344ej.ondigitalocean.app
    - key: CORS_ORIGIN
      value: https://operator-344ej.ondigitalocean.app
    - key: TRUST_PROXY
      value: '1'  # Trust first proxy
  
  # Health Check Configuration
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
    port: 3420
  
  # HTTP Headers Configuration
  http_headers:
    - name: X-Robots-Tag
      value: "noindex, nofollow"
    - name: X-Frame-Options
      value: "DENY"
    - name: X-Content-Type-Options
      value: "nosniff"
    - name: Referrer-Policy
      value: "same-origin"
    - name: Permissions-Policy
      value: "camera=(), microphone=(), geolocation=()"
    - name: Set-Cookie
      value: "__cf_bm=; Path=/; Domain=operator-344ej.ondigitalocean.app; Secure; HttpOnly; SameSite=None; Max-Age=14400"

  # Static file serving configuration
  static_assets:
    - path: /
      directory: /app/dist
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    
    # Serve bruno_demo_temp directory
    - path: /bruno_demo_temp
      directory: /app/bruno_demo_temp
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    
    # Other static assets
    - path: /js
      directory: /app/public/js
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    - path: /vendors
      directory: /app/public/vendors
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    - path: /models
      directory: /app/public/models
    - path: /textures
      directory: /app/public/textures
    - path: /assets
      directory: /app/public/assets
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
  
  # Resource Configuration
  resources:
    cpu: 1000m
    memory: 2048
