name: operator-nexus
region: nyc
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: dexters-lab-ai/Nexus
  dockerfile_path: Dockerfile
  http_port: 3420  # Production port
  instance_size_slug: professional-xs
  instance_count: 1
  
  # Environment variables
  envs:
    # Server Configuration
    - key: NODE_ENV
      value: production
    - key: PORT
      value: '3420'
    - key: NODE_OPTIONS
      value: --max-old-space-size=4096
    
    # API Configuration
    - key: APP_DOMAIN
      value: operator.dexter-ai.io
    - key: VITE_API_URL
      value: https://operator.dexter-ai.io
    - key: VITE_WS_URL
      value: wss://operator.dexter-ai.io
    - key: API_URL
      value: https://operator.dexter-ai.io
    - key: FRONTEND_URL
      value: https://operator.dexter-ai.io
    - key: WS_URL
      value: wss://operator.dexter-ai.io
    - key: OPERATOR_APP_WS_URL
      value: wss://operator.dexter-ai.io/ws
    
    # Security
    - key: SECURE_COOKIES
      value: 'true'
    - key: COOKIE_DOMAIN
      value: operator.dexter-ai.io
    - key: SAME_SITE_COOKIE
      value: 'none'
    - key: CORS_ORIGIN
      value: https://operator.dexter-ai.io
    - key: TRUST_PROXY
      value: '1'
    
    # Midscene Configuration
    - key: MIDSCENE_MODEL_NAME
      value: gpt-4o-mini
    - key: MIDSCENE_RUN_DIR
      value: /app/nexus_run

    # Secrets - These should be set in DigitalOcean dashboard
    - key: SESSION_SECRET
      scope: RUN_AND_BUILD_TIME
      value: ${SESSION_SECRET}
    - key: MONGO_URI
      scope: RUN_AND_BUILD_TIME
      value: ${MONGO_URI}
    - key: WEBHOOK_SECRET
      scope: RUN_AND_BUILD_TIME
      value: ${WEBHOOK_SECRET}
    - key: WS_SECRET
      scope: RUN_AND_BUILD_TIME
      value: ${WS_SECRET}
    - key: OPENAI_API_KEY
      scope: RUN_AND_BUILD_TIME
      value: ${OPENAI_API_KEY}
    - key: HF_API_KEY
      scope: RUN_AND_BUILD_TIME
      value: ${HF_API_KEY}
    - key: JWT_SECRET
      scope: RUN_AND_BUILD_TIME
      value: ${JWT_SECRET}
    
    # API Keys and Config
    - key: GOOGLE_API_KEY_FILE
      value: config/google-key.json
    - key: WEBHOOK_URL
      value: https://operator.dexter-ai.io/api/webhook

  # Health Check Configuration
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
    port: 3420

  # Static file serving configuration
  static_assets:
    - path: /
      directory: /app/dist
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    - path: /public
      directory: /app/public
      headers:
        - name: Cache-Control
          value: "public, max-age=86400"
    
    # Serve bruno_demo_temp directory
    - path: /bruno_demo_temp
      directory: /app/bruno_demo_temp
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    
    # Other static assets
    - path: /js
      directory: /app/public/js
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    - path: /vendors
      directory: /app/public/vendors
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
    - path: /models
      directory: /app/public/models
    - path: /textures
      directory: /app/public/textures
    - path: /assets
      directory: /app/public/assets
      headers:
        - name: Cache-Control
          value: "public, max-age=31536000, immutable"
  
  # Resource Configuration
  resources:
    cpu: 1000m
    memory: 2048