version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-app
    ports:
      - "3420:3420"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3420
    volumes:
      # Persist data between container restarts
      - nexus_data:/usr/src/app/nexus_run
      # Mount config directory for API keys
      - ./config:/usr/src/app/config:ro
      # Mount public assets
      - ./public:/usr/src/app/public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3420/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 1G

# Define volumes for persistent data
volumes:
  nexus_data:
    name: nexus_app_data
