version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexus-app
    
    # Use host network for better Android device access
    network_mode: host
    
    # Explicitly expose ports for documentation
    ports:
      - "3000:3000"  # Frontend
      - "3420:3420"  # Backend API
      - "24678:24678" # Vite HMR
      - "5554-5585:5554-5585" # Android ADB ports
      - "27017:27017" # MongoDB
    
    environment:
      - NODE_ENV=production
      - DOCKER=true
      - PORT=3420
      - VITE_API_URL=http://localhost:3420
      - VITE_WS_URL=ws://localhost:3420
      - FRONTEND_URL=http://localhost:3000
      - APP_DOMAIN=localhost
      - NEXUS_RUN_DIR=/usr/src/app/nexus_run
      - ANDROID_HOME=/opt/android-sdk
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk/platform-tools
      # Enable debug logging if needed
      # - DEBUG=midscene:*
    
    # Required for USB device access
    privileged: true
    
    # Mount USB devices for Android access
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # All USB devices
      - "/dev/kvm:/dev/kvm"           # For Android emulator
    
    # Additional Linux capabilities
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN
    
    # Required for udev to detect devices
    tmpfs:
      - /dev/bus/usb
    
    volumes:
      # Mount source code
      - .:/usr/src/app
      # Keep node_modules and .vite in container to avoid permission issues
      - /usr/src/app/node_modules
      - /usr/src/app/.vite
      # Persistent data
      - nexus_data:/usr/src/app/nexus_run
      # Mount config directory for API keys (read-only)
      - ./config:/usr/src/app/config:ro
      # Android SDK and devices
      - android-sdk:/opt/android-sdk
      # For adb key storage
      - android-adb:/root/.android
      # For adb server
      - /tmp/.android:/tmp/.android
      # Mount the host's udev database
      - /run/udev:/run/udev:ro
    
    working_dir: /usr/src/app
    
    # Use tini as init process to handle signals properly
    init: true
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Container resource limits
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    
    # Enable auto-restart unless stopped
    restart: unless-stopped
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

# Named volumes for persistent data
volumes:
  nexus_data:
    name: nexus_app_data
    driver: local
  android-sdk:
  android-adb:
