services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexus-app
    ports:
      - "3420:3420"
      - "3000:3000"  # For Vite dev server
    environment:
      - NODE_ENV=development
      - DOCKER=true
      - PORT=3420
      - VITE_API_URL=http://localhost:3420
      - VITE_WS_URL=ws://localhost:3420
      - FRONTEND_URL=http://localhost:3000
      - APP_DOMAIN=localhost
      - NEXUS_RUN_DIR=/usr/src/app/nexus_run
      # Enable Vite debug logging
      - DEBUG=vite:*
    volumes:
      # Mount source code for hot reloading
      - .:/usr/src/app
      # Keep node_modules in container to avoid permission issues
      - /usr/src/app/node_modules
      # Persistent data
      - nexus_data:/usr/src/app/nexus_run
      # Mount config directory for API keys (read-only)
      - ./config:/usr/src/app/config:ro
    working_dir: /usr/src/app
    # Use tini as init process to handle signals properly
    init: true
    # Container resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    # Enable auto-restart unless stopped
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3420/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

# Volumes for persistent data
volumes:
  nexus_data:
    name: nexus_app_data
    driver: local
