services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexus-app
    # Use host network for better performance in development
    network_mode: host
    # Explicitly expose ports for documentation
    expose:
      - "3000"  # Vite dev server
      - "3420"  # Backend API
      - "24678" # Vite HMR
    environment:
      - NODE_ENV=development
      - DOCKER=true
      - PORT=3420
      # Use host.docker.internal for accessing host services
      - VITE_API_URL=http://host.docker.internal:3420
      - VITE_WS_URL=ws://host.docker.internal:3420
      - FRONTEND_URL=http://localhost:3000
      - APP_DOMAIN=localhost
      - NEXUS_RUN_DIR=/usr/src/app/nexus_run
      # Enable debug logging if needed
      #- DEBUG=vite:*
    volumes:
      # Mount source code for hot reloading
      - .:/usr/src/app
      # Keep node_modules and .vite in container to avoid permission issues
      - /usr/src/app/node_modules
      - /usr/src/app/.vite
      # Persistent data
      - nexus_data:/usr/src/app/nexus_run
      # Mount config directory for API keys (read-only)
      - ./config:/usr/src/app/config:ro
      # Enable polling for file changes in development
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./index.html:/usr/src/app/index.html
    working_dir: /usr/src/app
    # Use tini as init process to handle signals properly
    init: true
    # Container resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    # Enable auto-restart unless stopped
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

# Volumes for persistent data
volumes:
  nexus_data:
    name: nexus_app_data
    driver: local