version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://operator-io236.ondigitalocean.app
        - VITE_WS_URL=wss://operator-io236.ondigitalocean.app
        - FRONTEND_URL=https://operator-io236.ondigitalocean.app
        - APP_DOMAIN=operator-io236.ondigitalocean.app
    container_name: nexus-app
    ports:
      - "3420:3420"
    # Environment variables are now passed directly rather than through .env file
    environment:
      - NODE_ENV=production
      - PORT=3420
      - VITE_API_URL=https://operator-io236.ondigitalocean.app
      - VITE_WS_URL=wss://operator-io236.ondigitalocean.app
      - FRONTEND_URL=https://operator-io236.ondigitalocean.app
      - APP_DOMAIN=operator-io236.ondigitalocean.app
      - DOCKER=true
      - NEXUS_RUN_DIR=/usr/src/app/nexus_run
    volumes:
      # Persist data between container restarts
      - nexus_data:/usr/src/app/nexus_run
      # Mount config directory for API keys (read-only)
      - ./config:/usr/src/app/config:ro
      # Mount public assets
      - ./public:/usr/src/app/public:ro
    # Ensure the container has enough resources
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3420/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

# Volumes for persistent data
volumes:
  nexus_data:
    name: nexus_app_data
    driver: local
