version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # Ensure we're using the production stage from Dockerfile
    container_name: nexus-app
    
    # Use host network for better Android device access
    network_mode: host
    
    environment:
      - NODE_ENV=production
      - DOCKER=true
      # Puppeteer/Chromium settings
      - CHROME_BIN=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      # Node.js memory settings
      - NODE_OPTIONS=--max-old-space-size=4096
      # Android settings
      - ANDROID_HOME=/opt/android-sdk
      - NEXUS_RUN_DIR=/usr/src/app/nexus_run
    
    # Required for USB device access
    privileged: true
    
    # Required for Android device access
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # All USB devices
    
    # Explicitly set the command to ensure it's using the production build
    command: node --max-old-space-size=4096 server.js
    
    # Resource limits - increased for Chromium and Android
    deploy:
      resources:
        limits:
          cpus: '4'  # Increased for Android emulation
          memory: 8G  # Increased for Android emulation
    
    # Health check with curl (lighter than wget)
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3420/api/health', r => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Configure logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Shared memory settings for Chromium
    shm_size: 2gb  # Increased for Android
    
    # Port mappings
    ports:
      - "3000:3000"  # Frontend
      - "3420:3420"  # Backend API
      - "24678:24678" # Vite HMR
      - "5554-5585:5554-5585" # Android ADB ports
      - "27017:27017" # MongoDB
    
    # Volumes for persistent data and Android
    volumes:
      - ./nexus_run:/usr/src/app/nexus_run
      - ./logs:/usr/src/app/logs
      # Android SDK
      - android-sdk:/opt/android-sdk
    
    # DNS configuration for better network performance
    dns:
      - 1.1.1.1
      - 8.8.8.8
    
    # Set ulimits for better stability
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    
    # Use tini as init process to handle signals properly
    init: true

# Named volumes for persistent data
volumes:
  nexus_data:
    name: nexus_app_data
    driver: local
  android-sdk:
